language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U platformio
script:
  - platformio update
  - rm -rf ~/.platformio/packages/framework-energiativa/libraries/AIR430*
  - patch ~/.platformio/packages/framework-energiativa/libraries/OneMsTaskTimer/OneMsTaskTimer.cpp -i enable-onemstasktimer.patch
  - platformio run
